### ISSUE TITLE
Design Card Layout (Holidays Page)

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/home-for-the-holidays#10]
## User Story
• As a user upon login I should see a page of cards depicting basic holidays. 

## Dev Notes
• Import jQuery
• Create bootstrap cards for Holiday Layout. 
[Bootstrap cards link](http://getbootstrap.com/docs/4.1/components/card/)
• Create string builder to populate the Holiday cards from the API call. 

## Acceptance Criteria
• After the user logs in there should be a page of cards displaying holidays.

**Comment by zoeames** [comment]
no longer needed
