### ISSUE TITLE
Display person card after drop down selection

### ISSUE THREAD

**Issue by jsmnwltrs** [nss-evening-cohort-8/home-for-the-holidays#15]
### User Story
As a user, when I select a name in the drop down, I need a single person view to display below that shows me the person's data.

### Acceptance Criteria
- When a person is selected in the drop down, friends name displays.
- If another person is selected a different name displays. (they don't append) 

### Tech Notes
- Create a 'click' event that takes the value attribute of the selected person
- Make axios call to get the friend
- Display friend's name

**Comment by zoeames** [comment]
duplicate
