### ISSUE TITLE
Holiday Setup

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/home-for-the-holidays#18]
## User Story
• As a developer I need holiday.js, holiday.scss & holidayData.js files to build the holiday page. 

## Dev Notes
• in the components folder, create a holiday folder
• in the data folder, create holidayData.js
• create holiday.js & holiday.scss & holidayEvents.js
• in holiday.js import holiday.scss
• import bootstrap in holiday.js & holiday.scss
• in holidayData.js import Axios

## Acceptance Criteria
• The components folder contains all required folders/files created and console log from js files and background color changed from the scss.

**Comment by zoeames** [comment]
duplicates #25
