### ISSUE TITLE
Updating Data in JSON file- after holiday has been added or edited

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-8/home-for-the-holidays#23]
# User Story
As a user, I should be able to save my new holiday or my edited changes on the holiday page.

# Acceptance Criteria
- The holiday array in your JSON file should be updated to account for your new changes. 

# Tech Notes
- JSON data updated with the saved changes
- Firebase

**Comment by zoeames** [comment]
no longer needed
