### ISSUE TITLE
Holiday Card Click Event

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/home-for-the-holidays#27]
## User Experience
• As a user when I click on a holiday card I should be taken to the Holiday Summary page.  

## Dev Notes
• Create a click event in the holidayEvents.js to handle clicking anywhere on card. 
• Console log to verify event is firing. 

## Acceptance Criteria
• The event is written to console log.

**Comment by zoeames** [comment]
no longer needed
