### ISSUE TITLE
Modal Box

### ISSUE THREAD

**Issue by Waysidetester** [nss-evening-cohort-8/home-for-the-holidays#3]
## User Story
As a user, when the modal box appears, I should see the following:
• Search bar
• "Favorites" button
• "All" button
• A list of all of my friends with checkboxes next to each one
• Save button 
• Cancel button

## Tech Notes
• Modal should not appear until the button is actually clicked 
• Dynamically print the modal to the page 

## Acceptance Criteria
• I should be able to interface with the modal and see all of the features listed above

**Comment by lancehamilton24** [comment]
![invitationlistmoqup](https://user-images.githubusercontent.com/26915483/48386069-6653bb80-e6b6-11e8-8c16-8c1923a8400a.PNG)

**Comment by zoeames** [comment]
no longer needed
