### ISSUE TITLE
Print Attendees to Holiday Page

### ISSUE THREAD

**Issue by TimothyHarley** [nss-evening-cohort-8/home-for-the-holidays#31]
### User Story
As a user, I want to see a list of all the guests that are invited to that Holiday.  Guests that are flagged as unfavorable will be highlighted red. 

### Acceptance Criteria
The invited guests email guests names, email, and phone number should be displayed in the guests div.  flagged guests will be highlighted.

### Tech Notes
Call a function to loop over the guest array and have an 'if' statement for the flagged guests.  include a string builder of some kind to print all the relevant information.

**Comment by zoeames** [comment]
duplicates #30
