### ISSUE TITLE
Edit Button on Holiday Card View

### ISSUE THREAD

**Issue by marshalloffutt** [nss-evening-cohort-8/home-for-the-holidays#33]
## User Story
As a user if I want to edit Holiday details, can do so simply by clicking on the Edit button that will depicted as a small graphic of a pencil.

## Acceptance Criteria
When I click the pencil button, I am able to edit details of the Holiday.

## Technical Notes
- Click event calls the edit function from Card #32

**Comment by zoeames** [comment]
event now part of #16
