### ISSUE TITLE
Print friends to Modal

### ISSUE THREAD

**Issue by Waysidetester** [nss-evening-cohort-8/home-for-the-holidays#4]
### User Experience
As a user, I should be able to see all of my friends' names in a list with a checkbox next to each name.

### Acceptance Criteria
* Must have the ability to select individual friend names and add them to the invitation list. 

### Dev Notes
* Create string builder with a printToDom function that prints the friends list using an axios call from Firebase.

**Comment by zoeames** [comment]
duplicated #2
