### ISSUE TITLE
Initialize Holiday Card View (click event)

### ISSUE THREAD

**Issue by marshalloffutt** [nss-evening-cohort-8/home-for-the-holidays#9]
## User Story
As a user when I click on a holiday I should see a new page with holiday details, and list of invited guests. So I can learn more about the holiday.

## Acceptance Criteria
New page loads when holiday card is clicked.

## Tech Notes
- Event listener for the holiday cards, which will function as buttons.
- Click anywhere on card, use closest method to grab the Holiday Id.

**Comment by zoeames** [comment]
no longer needed
